spring.application.name=master.prompt.tamplate

#Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.temperature=0.5
#spring.ai.chat.client.enabled=false
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
